trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: make -j$(nproc --all) -C bsnes
  displayName: 'Build'

- script: zip bsnes-hd.zip bsnes/out/bsnes.app ../../LICENSE ../../README.md
  displayName: 'Create archive'

- publish: $(System.DefaultWorkingDirectory)/bin/WebApp
  artifact: bsnes-hd_macos
