trigger:
- master

pool:
  vmImage: 'macOS-10.14'

steps:
- script: make -j$(nproc --all) -C bsnes
  displayName: 'Build'

- script: |
    ls
    echo cd bsnes && ls
    cd bsnes && ls
    echo cd out && ls
    cd out && ls
    #zip
  displayName: 'Create archive'
